### ISSUE TITLE
Abnormal amount of updates

### ISSUE THREAD

**Issue by areyoufserious** [fufar/simple-clock-card#6] opened 2021-04-07 02:50 UTC
In dev tools, i can see that DIV with clock updates tens of times per second. Why you do that? If it's a bug -- please, fix it.

**Comment by fufar** [comment] 2021-04-11 19:02
I'm not a js coder - so i don't know how to fix it. It doesn't seem to cause problems or high load, so lets keep it. If someone want to fix it - PR is welcomed :)

**Comment by martin131** [comment] 2021-04-11 20:09
My tablet in kiosk mode is discharging with charger plugged in. After removing clock from Lovelace it is working good. I think it is caused by this bug.

**Comment by areyoufserious** [comment] 2021-04-24 01:44
> My tablet in kiosk mode is discharging with charger plugged in. After removing clock from Lovelace it is working good. I think it is caused by this bug.

Absolutely
And I don't understand how an author can ignore such feedbacks, especially if he is not a developer and can't have appropriate understanding and reaction.

**Comment by fufar** [comment] 2021-04-24 15:14
> > My tablet in kiosk mode is discharging with charger plugged in. After removing clock from Lovelace it is working good. I think it is caused by this bug.
> 
> Absolutely
> And I don't understand how an author can ignore such feedbacks, especially if he is not a developer and can't have appropriate understanding and reaction.

you can write or make issue to orignial author https://github.com/arjhun/Homeassistant-Lovelace-Cards
My part - add it to hacs because arjhun https://github.com/arjhun/Homeassistant-Lovelace-Cards/issues/2#issuecomment-748895393  didnt want it, and few small changes which i can do without js understanding

**Comment by fufar** [comment] 2021-04-24 15:15
i reopen it, but it will wait untill someone help

**Comment by tomasz-s** [comment] 2021-04-25 02:14
> > My tablet in kiosk mode is discharging with charger plugged in. After removing clock from Lovelace it is working good. I think it is caused by this bug.
> 
> Absolutely
> And I don't understand how an author can ignore such feedbacks, especially if he is not a developer and can't have appropriate understanding and reaction.

Noticed today I have big problems with switching tabs on my tablet. I've tested with Chrome, Native App, WallPanel App....  
switching between tabs was about 10 seconds. 
Hint was... tab switching was problematic only from page with clock card....,  then I found this thread.

Long story short, just pushed my quick fix. https://github.com/fufar/simple-clock-card/pulls

**Comment by fufar** [comment] 2021-04-25 13:33
merged in https://github.com/fufar/simple-clock-card/releases/tag/1.4
for me working ok, hope for everyone too
thx @tomasz-s

**Closed** 2021-04-27 09:43 UTC
Labels: help wanted
